logging-to-file = true        # enables logging of every patch process to a seperate file
enable-magisk-update = true   # set this to false if you do not want to receive updates for the module in magisk app

# add 'enabled = false' for not patching a specific app or remove it from the config
# see https://github.com/j-hc/revanced-magisk-module/blob/main/CONFIG.md for more detailed explanations

[YouTube]
enabled = false
build-mode = "both"                                                   # 'both', 'apk' or 'module'
excluded-patches = "custom-branding debugging spoof-app-version"                                                 # space-seperated patches to exclude (multiline strings are not supported)
included-patches = ""                                                 # space-seperated patches to include (non-excluded patches are included by default)
version = "auto"                                                      # 'auto', 'latest', 'beta' or a custom one like '17.40.41'
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube/"

[Music-Extended] # unmaintained
enabled = false
app-name = "Music"
patches-source = "inotia00/revanced-patches"
integrations-source = "inotia00/revanced-integrations"
cli-source = "inotia00/revanced-cli"
rv-brand = "ReVanced Extended"
build-mode = "both"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube-music/"
apkmirror-arch = "both"

[YouTube-Extended] # unmaintained
enabled = true
app-name = "YouTube"
patches-source = "YT-Advanced/ReX-patches"
integrations-source = "YT-Advanced/ReX-integrations"
cli-source = "ReVanced/revanced-cli"
rv-brand = "Youtube"
build-mode = "both"
excluded-patches = ""
included-patches = "add-splash-animation bypass-ambient-mode-restrictions custom-seekbar-color disable-shorts-on-startup enable-external-browser enable-minimized-playback enable-old-quality-layout enable-seekbar-tapping force-premium-heading hide-auto-player-popup-panels hide-channel-watermark hide-general-ads hide-video-ads optimize-resource return-youtube-dislike settings sponsorblock spoof-player-parameters"
exclusive-patches = true
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube/"
