compression-level = 9         # compression level for module zips. between 1 and 9
logging-to-file = true        # enables logging of every patch process to a seperate file
enable-magisk-update = true   # set this to false if you do not want to receive updates for the module in magisk app
parallel-jobs = 1             # max number of concurrent building jobs
build-mindetach-module = true

# add 'enabled = false' for not patching a specific app or remove its entry
# see https://github.com/j-hc/revanced-magisk-module/blob/main/CONFIG.md for more detailed explanations

[YouTube]
enabled = true
build-mode = "both"                                                   # 'both', 'apk' or 'module'
excluded-patches = ""                                        # whitespace seperated list of patches to exclude (multiline strings are not supported)
included-patches = "client-spoof custom-video-buffer custom-video-speed disable-shorts-on-startup downloads general-ads hide-watermark minimized-playback old-quality-layout open-links-externally premium-heading remember-playback-rate remember-video-quality return-youtube-dislike seekbar-tapping sponsorblock video-ads"                                                 # whitespace seperated list of patches to include
version = "auto"                                                      # 'auto', 'latest' or a custom one like '17.40.41'
exclusive-patches = true                                             # excludes all patches by default
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube/"
module-prop-name = "ytrv-maxgisk"
